Add display fallback
aehrc/fhir-claml pull request #2
Opened 2020-03-23 22:51 UTC by patrick-werner

added a -dFallback option allowing you to define a fallback for -d if this rubik wasn't found in the class.

2020-03-24 00:17 UTC, jimsteel requested changes

2020-03-24 00:17 UTC, jimsteel commented on src/main/java/au/csiro/fhir/claml/FhirClamlService.java
> -            output.getParentFile().mkdirs();
Does this revert #1?

2020-03-24 07:09 UTC, patrick-werner commented on src/main/java/au/csiro/fhir/claml/FhirClamlService.java
> -            output.getParentFile().mkdirs();
yes, it did, good catch.

2021-08-18 12:48 UTC, patrick-werner commented
closing as desired changes already applied through: https://github.com/aehrc/fhir-claml/commit/348e887896d3c53520bf0759d962e0492d2ed33c

2021-08-18 12:48 UTC, closed without merging